#!/bin/bash

if ! tmux ls > /dev/null 2>&1; then exit; fi

editors="vim|vi|nvim|emacs"
DEST_DIR=~/.tmux-sessions/
HOST=$(hostname -s)

mkdir -p $DEST_DIR

detect_editor_cmd() {
    root_pid="$1"

    # Get all descendant PIDs of the root_pid
    get_descendants() {
        local parent=$1
        local children=$(ps -eo pid=,ppid= | awk -v p="$parent" '$2==p {print $1}')
        for pid in $children; do
            echo "$pid"
            get_descendants "$pid"
        done
    }

    # Include the root pid itself
    all_pids="$root_pid $(get_descendants "$root_pid")"

    for pid in $all_pids; do
        # Get the full command for each PID
        cmd=$(ps -p "$pid" -o command= 2>/dev/null)
        if [[ "$cmd" =~ (^|[[:space:]])($editors)([[:space:]]|$) ]]; then
            echo "$cmd"
            return 0
        fi
    done

    return 1  # No editor found
}

tmux list-sessions -F "#{session_name}" | while read -r line ; do
  session=$(echo $line | cut -d ' ' -f 1)
  rm -f $DEST_DIR/${HOST}-${session}*

  rm -f $DEST_DIR/${HOST}-${session}-panes
  tmux list-panes -a -t $session -F "#{session_name} #{window_index} #{window_name} #{pane_index} #{window_layout}" | while read -r pane ; do
    if (( $(echo $pane | cut -d ' ' -f 1) == $session )) ; then
      echo $pane >> $DEST_DIR/${HOST}-${session}-panes
    fi
  done

  while read line; do
    #session=$(echo "$line" | cut -d ' ' -f 1)
    window=$(echo "$line" | cut -d ' ' -f 2)
    wname=$(echo "$line" | cut -d ' ' -f 3)
    pane=$(echo "$line" | cut -d ' ' -f 4)
    pid=$(tmux display-message -p -t $session:$window.$pane -F "#{pane_pid}")
    fname=$DEST_DIR/${HOST}-$session:$window.$pane

    tmux display-message -p -t $session:$window.$pane -F "#{pane_current_path}" > ${fname}-path

    tmux capture-pane -t $session:$window.$pane -epS -100000 > ${fname}
    #echo "PWD:" $(tmux display-message -p -t $session:$window.$pane -F "#{pane_current_path}") >> ${fname}
    detect_editor_cmd $pid >> ${fname}-cmd
    case $(uname -s) in
      Linux*)     pstree $pid -a >> ${fname}-cmd;;
      #Linux*)     ps f -g $pid >> ${fname}-cmd;;
      Darwin*)    pstree $pid >> ${fname}-cmd;;
      *)          exit 0
    esac
  done < $DEST_DIR/${HOST}-${session}-panes

done

echo "Saved"
